server:
  port: 8081

spring:
  devtools:
    restart:
      enabled: true

    livereload:
      enabled: true

  freemarker:
    cache: false

  thymeleaf:
    cache: false

  data:
    maria:
      jdbc-url: jdbc:mariadb://localhost:3306/inha_notice_board?useUnicode=yes&characterEncoding=UTF-8
      driver-class-name: org.mariadb.jdbc.Driver
      username: server
      password: dlsgk12#$%

  jpa:
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_feaults: false
    generate-ddl: true
